version: '3.1'
services:
    mysql:
        image: mysql:latest
        container_name: 
        environment:
            MYSQL_USER: ""
            MYSQL_PASSWORD: ""
            MYSQL_DATABASE: ""
            MYSQL_ROOT_PASSWORD: "root"
        ports:
            - 3306:3306
        restart: always

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: 
        links:
            - mysql
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
            PMA_ARBITRARY: 1
        restart: always
        ports:
            - 8001:80